name: Publish Crate

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Run clippy
      run: cargo clippy -- -D warnings
      shell: bash
      env:
        RUST_BACKTRACE: full

    - name: Run tests
      run: cargo test
      env:
        CARGO_TARGET_DIR: target

    - name: Publish to crates.io
      run: cargo publish --token $CRATES_REGISTRY_TOKEN
      env:
        CRATES_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
